services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectdb      
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./project
    container_name: app    
    command: "node index.js"    
    tty: true
    depends_on:
      db:
        condition: service_healthy      

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
